[package]
name = "tn-mir"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
tn-diagnostics = { path = "../tn-diagnostics" }
tn-hir = { path = "../tn-hir" }

[lints]
workspace = true
